require "securerandom"
require "phonetic"
require "syllabize"
require "calyx"
require "prawn"

require_relative "bitspeech"
require_relative "word"
require_relative "rhyme"
require_relative "lexicon"
require_relative "sonnet"
require_relative "rhyme_scheme"
require_relative "poem"
require_relative "stanza"
require_relative "book"
require_relative "document"
require_relative "cover_swatch"
